name: 'GitHub Actions Mirror'
on: [push, delete]
jobs:
  mirror_to_gitee:
    runs-on: windows-latest
    steps:
      - name: Mirror the Github organization repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/Truman1970
          dst: gitee/Truman1970
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
